name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: 7rlnN8DnBXZ57TftXkOibKDy8mQRZLvrmW13-8BF
          
      - run: npm install
      
      - name: Configure EAS project
        run: eas build:configure --platform android --non-interactive
        env:
          EXPO_TOKEN: 7rlnN8DnBXZ57TftXkOibKDy8mQRZLvrmW13-8BF
          
      - name: Build APK
        run: eas build --platform android --profile preview --local --output ./app.apk --non-interactive
        env:
          EXPO_TOKEN: 7rlnN8DnBXZ57TftXkOibKDy8mQRZLvrmW13-8BF
          
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./app.apk
          
      - uses: softprops/action-gh-release@v1
        with:
          files: ./app.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
